[package]
name = "smarty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
dotenv = "0.15.0"
poise = { version = "0.5.2", features = ["collector", "time"] }
tokio = { version = "1.27.0", features = ["full"] }
dotenv_codegen = "0.15.0"
chrono = "0.4.24"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.7" }
serde = "1.0.159"

[workspace]
members = ["prismaclient"]
