services:
  cache:
    build: ./crates/cache
    container_name: cache
    image: onlycs/oreobot:v2-cache
    networks:
      - oreonet

  logger:
    build: ./crates/logger
    container_name: logger
    image: onlycs/oreobot:v2-logger
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - oreonet

  bot:
    build: ./crates/bot
    container_name: bot
    image: onlycs/oreobot:v2-bot
    networks:
      - oreonet
    depends_on:
      - logger
      - cache

networks:
  oreonet:
    driver: bridge
    name: oreonet
