services:
  cache:
    build: ./crates/cache
    networks:
      - oreonet

  logger:
    build: ./crates/logger
    networks:
      - oreonet

  bot:
    build: ./crates/bot
    networks:
      - oreonet

networks:
  oreonet:
    driver: bridge
