[alias]
prisma = "run -p oreo-prisma --bin prisma-cli --features=bin --"
prisma-release = "run -p oreo-prisma --bin prisma-cli --features=bin --release --"

[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
