[alias]
prisma = "run -p prisma-cli --"
prisma-release = "run -p prisma-cli --release --"

[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
