[alias]
prisma = "run -p oreo-prisma --bin prisma-cli --features=bin --"
prisma-release = "run -p oreo-prisma --bin prisma-cli --features=bin --release --"

[registries.crates-io]
protocol = "sparse"
