name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run client
        run: |
          cd deploy
          echo ${{ secrets.DOTENV }} >> .env
          cargo run --bin client
