name: dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Clone repo
          uses: actions/checkout@v2
        
        - name: Deploy to Dokku
          uses: dokku/github-action@master
          with:
            branch: main
            git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}/${{ secrets.DOKKU_APP_NAME }}
            ssh_private_key: ${{ secrets.SSH_KEY }}